services:
  spring-api-image:
    image: spring-api-image
    container_name: Spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-networks
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: ken123
      MYSQL_DATABASE: homework
      MYSQL_USER: adminUser
      MYSQL_PASSWORD: 321
    ports:
      - "3307:3306"
    networks:
      - spring-networks
    volumes:
      - mysql-volumes:/var/lib/mysql


networks:
  spring-networks:

volumes:
  mysql-volumes:


